[package]
name = "reticulum-packet-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reticulum-packet-rs = "0.1.0"
clap = {version = "4.1.4", features = ["derive"]}
