* Overview
A simple Reticulum packet viewer that works via capturing the output of `tshark`. Build on top
of [[https://crates.io/crates/reticulum-packet-rs][reticulum-packet-rs]]. This
is a proof-of-concept and not properly versioned, as such it requires the
latest git version of reticulum-packet-rs most of the time to work.

* Usage
Assuming we want to caputer all packets from/to the Frankfurt testnet node:
#+BEGIN_SRC
sudo unbuffer tshark -T fields -e data host frankfurt.connect.reticulum.network | ~/reticulum-packet-viewer
#+END_SRC

By default, it will output in stderr some human readable information about the
received packets. If the =-v/--verbose= flag is passed, the =data= part of the
packet will also be printed as a list of 2 hex characters.

The =--announce= flag will also output the app data part of any received
announcements.

The =--filter= flag followed by a Reticulum address, will make it so that only
packets that match the provided address in one of the two address fields of the
header will be displayed.

* Output
This is an example output when requesting the Unsigned.io node on Reticulum:
#+BEGIN_SRC
Hop Address: 0D6894447781844E3392C845E843886A, Address: EC58B0E430CD9628907383954FEEA068, Hops: 0, Header Type: 2, Context: None, Destination Type: Single, Propagation Type: Transport, Packet Type: Linkrequest
Address: 73339B600B581C61F558C1FEBD2DE619, Hops: 1, Header Type: 1, Context: Lrproof, Destination Type: Single, Propagation Type: Broadcast, Packet Type: Proof
Address: 73339B600B581C61F558C1FEBD2DE619, Hops: 0, Header Type: 1, Context: Lrrtt, Destination Type: Link, Propagation Type: Broadcast, Packet Type: Data
Address: 73339B600B581C61F558C1FEBD2DE619, Hops: 0, Header Type: 1, Context: Request, Destination Type: Link, Propagation Type: Broadcast, Packet Type: Data
Address: 73339B600B581C61F558C1FEBD2DE619, Hops: 1, Header Type: 1, Context: ResourceAdv, Destination Type: Link, Propagation Type: Broadcast, Packet Type: Data
Address: 73339B600B581C61F558C1FEBD2DE619, Hops: 0, Header Type: 1, Context: ResourceReq, Destination Type: Link, Propagation Type: Broadcast, Packet Type: Data
Address: 73339B600B581C61F558C1FEBD2DE619, Hops: 1, Header Type: 1, Context: Resource, Destination Type: Link, Propagation Type: Broadcast, Packet Type: Data
Address: 73339B600B581C61F558C1FEBD2DE619, Hops: 1, Header Type: 1, Context: Resource, Destination Type: Link, Propagation Type: Broadcast, Packet Type: Data
Address: 73339B600B581C61F558C1FEBD2DE619, Hops: 0, Header Type: 1, Context: ResourcePrf, Destination Type: Link, Propagation Type: Broadcast, Packet Type: Proof
#+END_SRC
